package modelku;

// Generated Mar 13, 2015 12:57:16 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "restaurant")
public class Customer implements java.io.Serializable {

	private Integer id;
	private String name;
	//private Set<Order> orders = new HashSet<Order>(0);

	public Customer() {
	}

	public Customer(String name) {
		this.name = name;
	}

//	public Customer(String name, Set<Order> orders) {
//		this.name = name;
//		this.orders = orders;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
//	public Set<Order> getOrders() {
//		return this.orders;
//	}
//
//	public void setOrders(Set<Order> orders) {
//		this.orders = orders;
//	}

}
